### ISSUE TITLE
Great script!

### ISSUE THREAD

**Issue by vnunez85** [eneax/x-writer#8]
Hello, trying your app, and was able to launch it on Vercel and looks like it needs to. Im having an issue when I click the button to generate, if just spins. It was working correctly on my localhost, and it did generate, but not on Vercel. Am I missing something?

Thanks for the help!

**Comment by eneax** [comment]
Thank you for trying the app!

The problem is that OpenAI API request take up to 30 or 40 seconds to process if you use a very long prompt, but if you have a free Vercel plan, Serverless Functions timeout after 10 seconds.

From the [Vercel docs](https://vercel.com/docs/concepts/limits/overview#serverless-function-execution-timeout):
> The amount of time (in seconds) that a Serverless Function is allowed to process an HTTP request before it must respond. The maximum execution timeout is 10 seconds when deployed on a Personal Account (Hobby plan). For Teams, the execution timeout is 60 seconds (Pro plan) or 900 seconds (Enterprise plan).

To solve the timeout problem, you would have to get a paid Vercel plan or perhaps try another deployment service with a more generous free plan.
