### ISSUE TITLE
after adding .env.local

### ISSUE THREAD

**Issue by olastech1** [eneax/x-writer#9]
after adding .env.local still not generating content

**Comment by eneax** [comment]
Make sure to visit the OpenAI website first and get an [API key](https://beta.openai.com/account/api-keys).
Then, add `OPENAI_API_KEY=SECRET_KEY_OBTAINED_FROM_OPENAI` in the `.env.local` file.

**Comment by olastech1** [comment]
![Screenshot 2022-12-22 175804](https://user-images.githubusercontent.com/84507555/209187243-8143a056-e0da-4aca-bd45-1c10df01fa69.png)
![Screenshot 2022-12-22 175825](https://user-images.githubusercontent.com/84507555/209187246-ab153191-bdad-455a-9393-80cc6b741992.png)


i have done it still not wokring

**Comment by eneax** [comment]
The problem is that OpenAI API requests can take up to 30 or 40 seconds to process, but the deployment service you use might have a much shorter timeout limit for Serverless Functions.

To solve the timeout problem, you would have to get a paid plan or perhaps try another deployment service with a more generous free plan.

**Comment by olastech1** [comment]
oops

**Comment by olastech1** [comment]
wihch other deployment service can i use?

**Comment by eneax** [comment]
I'm not aware of any deployment service with a free plan that can handle the timeout limit for the Serverless function in this application. In fact, I have the same problem with my Vercel deployment.
